---
title: R 复习函数（加强学习）
author: Shuqiang
date: '2022-04-26'
slug: []
categories:
  - resource
tags:
  - R function

subtitle: ''
description: '实用的R函数，需要多看巩固；从别人脚本那学来的新函数'
image: ''

---
```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = TRUE, warning = FALSE,
                      message = FALSE, echo = TRUE, 
                      eval=FALSE,
                      dpi = 180, fig.width = 8, fig.height = 5)
library(tidyverse)
library('tidytext')
```

好滴 ~ 谢谢 ~ 那我感觉自己还需要再补充些shiny开发的知识、生信分析流程掌握；


```{r, eval=FALSE}
# parse_number: 直接提取第一个数字
parse_number(x = c('16.8 OA', '18 OA'))
# dplyr::add_count，计数添加到列
iris %>%
  add_count(Species) %>%
  head()
# rowise,mutate_if,across运算 行均值
# iris %>%
#   rowwise() %>%
#   mutate(row_mean = across(.cols = ends_with('th')) %>%
#               mean(na.rm = TRUE)) %>% head()
iris %>%
  rowwise() %>%
  mutate_if(is.numeric, log2) %>% head() 

# pivot_wider(data = , names_from = ####, values_from = ####, values_fill = 0)
# values_fill填补缺失值为0

# 对df中的列名去除空格，替换为_，这样列变量名看起来更舒服
# janitor::clean_names()

```


```{r, eval = FALSE}
# 将term排序，在每个component组内，按照values大小排序

# mutate(terms = reorder_within(x = terms, by = abs(values), within = component))
# scale_y_reordered() # 用于排序画图

# recipes::prep('Recipe') %>%
#   juice()

# PCA画图添加点的标签
# ggplot(aes(x = PC1, y = PC2, labels = VAR)) +
#   geom_text(check_overlap = TRUE, family = 'IBMPlexSans-Bold', hjust = 'inward')
# silgelib::theme_plex 选择
# umap降维，?embed::step_umap()
##########
#### PCA和Umap降维算法的区别
# https://blog.csdn.net/qq_43337249/article/details/116612811
# https://gwaslab.com/2021/09/16/umap/
# PCA:线性降维
# UMAP:非线性降维技术，与PCA不同，它视图找出样本的相似处然后collaping，其能够避免集群表示的过度拥挤，在重叠区域上能表示出不同的集群而被广泛运用
# 可以考虑对不同的降维方法画图比较。

## PCA画图，stat_ellipes(椭圆图，用于圈分类), annotate(添加文本/公式/圈点图等等)
# https://www.jianshu.com/p/14e1be78714f
# https://zhuanlan.zhihu.com/p/354086571
```


```{r}
# 生信分析火山图：双曲线图，不同于以往的线性划分
# https://www.jianshu.com/p/580395598150
```

```{r eval=TRUE}
# 给指定列批量操作，如得到每列的排序顺序

data <- tibble(
商品名称 = c("飞机","坦克","火车","汽车","电脑","微波炉","电冰箱"),
"20201" = c(1148180,936847.03,756678.94,661634.81,517844.34,515342.05,402535.4),
"20202" = c(724438,394463.6,299565.12,218171.05,77576.46,238128.77,84461.59),
"20203" = c(806344,599225.03,348673.68,287861.24,398617.05,294147.36,122243.58),
"20204" = c(1148928,985200.86,612672.88,576676.61,941509.14,520207.97,351694.72),
"20205" = c(1267112,509108.92,529845.63,831958.88,877673.16,362104.54,371722.34))

data %>% 
  mutate_if(is.numeric, list(rank = ~order(., decreasing = T))) %>% 
  colnames()

data %>% 
  mutate(across(-1, ~rank(-.x), .names = "{.col}_rank")) %>% 
  head(2)
```


## purrr包

这个包真的是精髓呀，需要重复学习使用

```{r eval =TRUE}
# 合并多个数组，求多个集合的共同交集
# 可能会考虑使用递归函数，这里介绍使用purrr函数

purrr::reduce(.x = list(1:3, 4:6, 7:9), .f = union)

purrr::reduce(.x = list(1:3, 2:5, 3:6 ), .f = intersect)


```

```{r eval=FALSE}
tidyverse::tidyverse_packages()
tidyverse::tidyverse_sitrep()
tidyverse::tidyverse_logo()
tidyverse::tidyverse_deps()
library(usethis)
library(devtools)
use_devtools()
use_github()
a <- 1
checkmate::assert_number(x = a)
```


### 查看已安装包及包信息

```{r}
available.packages() %>% 
  as_tibble() %>% 
  filter(str_detect(Package, 'tidyfst'))
```

