---
title: R/Python/电子书/生物信息 资料
author: Shuqiang
date: '2022-04-25'
slug: []
categories:
  - resource
tags:
  - Bio
  - Programing
  - Books
subtitle: ''
description: '介绍生物信息相关资料'
image: ''
---

### R

- [Julia Silge的个人Blog](https://juliasilge.com/blog/)：通过例子呈现数据分析  
- [`Tidy Modeling with R(tidymodels)`](https://www.tmwr.org/)：通过例子呈现数据分析  
- [TidyTuesday data set](https://github.com/rfordatascience/tidytuesday)  
- [TidyTuesday 实例脚本](https://hardin47.github.io/TidyTuesday/2022-03-22/babynames.html)  
- [mlr3社区](https://mlr3.mlr-org.com/)  
- [RStudio AI Blog](https://blogs.rstudio.com/ai/)  
- [RStudio Books](https://www.rstudio.com/resources/books/)  
- [R webinars(视频)](https://www.rstudio.com/resources/webinars/)  
- [tidyfst:相比tidyverse更高效处理数据](https://hope-data-science.github.io/tidyfst/)  
- [fst:高效读写GB级数据](https://github.com/fstpackage/fst)  
- [处理R高性能的专辑页Efficient R programing](https://csgillespie.github.io/efficientR/)  
- [处理R高性能的专辑页Advanced R](https://adv-r.hadley.nz/)  

### Python
- [Scikit-learn](https://scikit-learn.org/stable/index.html)
- [Pandas](https://pandas.pydata.org/pandas-docs/stable/getting_started/index.html#getting-started)  
- [Python Tech World(含热门库及博库,可查看DataWhale培训试题)](https://pythontechworld.com/)  
- [DataWhale](https://github.com/datawhalechina/joyful-pandas)  
- [python常用机器学习框架清单](https://blog.csdn.net/liuxiao723846/article/details/89070125)  
- [动手学深度学习](https://zh-v2.d2l.ai/index.html)  
- [深度学习的数学(https://xuzhougeng.top/archives/mathematics-basis-for-deep-learning)](https://book.douban.com/subject/33414479/)  
- [Python神经网络编程，入门神经网络的儿童读本](https://xuzhougeng.top/archives/a-good-book-for-who-want-to-learn-deep-learning)  


### 生物信息

- [生信常用网站导航](https://gwaslab.com/navigation/)  
- [生信编程框架](https://gwaslab.com/programming/)  
- []()  


### 电子书下载

- [鸠摩电子书下载](https://www.jiumodiary.com/)  
- [全球最大的数字图书馆：Z-library](https://pangniao.net/z-library-zui-xin-di-zhi.html)  
- [Bookdown开放书籍](https://bookdown.org)  

### 后端开发

- [GoLang全栈](https://hao.golangstack.com/)  
- []()


### 向往的达人

- [R数据科学家-刘思喆](https://bjt.name/2015/12/12/spark-or-r.html)  
  - [数据科学家能力素质模型](https://bjt.name/2021/09/28/statistician.html)  
- [统计之都](https://cosx.org/)  
- [Yixuan Qiu 上财教师](https://statr.me/categories/)  
- [怡然轩](https://yixuan.blog/cn/)  
- [黄湘云](https://xiangyun.rbind.io/)  
  - [符号计算与 R 语言](https://xiangyun.rbind.io/2016/07/r-symbol-calculate/)  
  - [开发企业级 Shiny 应用的技术栈](https://xiangyun.rbind.io/2021/08/shiny-in-production/)  
- [王诗翔](https://www.jianshu.com/u/b6608e27dc74)  

### 数据科学拓展

- [数据科学家的职业路径是什么?(EN)](https://www.business-science.io/careers/2022/03/15/the-data-science-career-path.html)  
- [数据科学家的职业路径是什么?(CH)](https://zhuanlan.zhihu.com/p/502353533)  
- [R语言必学之「data.table」学习资源合集](https://zhuanlan.zhihu.com/p/346366577)  
- [R数据处理|data.table篇（一）](https://zhuanlan.zhihu.com/p/26388833)  
- [在 R 中实现流程图](https://bjt.name/2009/02/21/r-flow-chart.html)  
- [统计之都：中国R语言会议](https://space.bilibili.com/22035559?spm_id_from=333.337.search-card.all.click)  
- [CSDN大数据技术大会](https://space.bilibili.com/217475729?spm_id_from=333.337.0.0)  


### 阅读记录(done)

> 
- [生死疲劳]()  
- [人类简史]()  

### 阅读记录(ing)

> `R shiny`  
- [Master Shiny with R](https://mastering-shiny.org/)  
- [Engineering Production-Grade Shiny Apps](https://engineering-shiny.org/)  
- [Outstanding User Interfaces with Shiny](https://unleash-shiny.rinterface.com/)  

> `R ML`  
- [特征工程和选择：预测模型的实用方法-R](https://bookdown.org/max/FES/important-concepts.html#model-bias-and-variance)  
- [Supervised Machine Learning for Text Analysis in R](https://smltar.com/)  
- [Welcome to Text Mining with R](https://www.tidytextmining.com/)  
- [mlr3 manual book](https://mlr3book.mlr-org.com/mlr3book.pdf)  
- [Advanced R(高级R语言编程)](https://adv-r.hadley.nz/S3.html)  
- [机器学习实战：使用R、tidyverse和mlr](https://book.douban.com/subject/35488867/?_dtcc=1)  

> `Python`  
- [Python 数据科学手册 by Jake VanderPlas]()  
